name: Run Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: vulture
      run: |
        vulture lazystuff .vulture-whitelist
    - name: pylint
      run: |
        pylint lazystuff
    - name: mypy
      run: |
        mypy lazystuff
    - name: pytest
      run: |
        pytest
